apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
  namespace: development
  labels:
    k8s-app: echo-app
  annotations:
    fluxcd.io/automated: "true"
    description: EchoApp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: echo-app
  template:
    metadata:
      name: echo-app
      labels:
        k8s-app: echo-app
      annotations:
        description: EchoApp
    spec:
      containers:
      - name: echo-app
        image: >-
          ba8d9c8fe1374d5bbf5913a537abc1b8.azurecr.io/echoapp:29c8f84e912e6d895104fb7f0618059105333ebb
        env:
        - name: AzureAD__ClientId
          valueFrom:
            secretKeyRef:
              name: echoad-credentials
              key: AzureAD__ClientId
        - name: AzureAD__TenantId
          valueFrom:
            secretKeyRef:
              name: echoad-credentials
              key: AzureAD__TenantId
      imagePullSecrets:
        - name: acr-secret-ba8d9c8fe-development
---
kind: Service
apiVersion: v1
metadata:
  name: echo-app-internal
  namespace: development
  labels:
    k8s-app: echo-app
  annotations:
    description: EchoApp
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    k8s-app: echo-app
---
# From https://docs.microsoft.com/en-us/azure/aks/ingress-basic
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-app-ingress-development
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - 52.188.77.165
    secretName: ihfdemo-tls
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: echo-app-internal
            port:
              number: 80

