apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
  namespace: development
  labels:
    k8s-app: echo-app
  annotations:
    fluxcd.io/automated: "true"
    description: EchoApp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: echo-app
  template:
    metadata:
      name: echo-app
      labels:
        k8s-app: echo-app
      annotations:
        description: EchoApp
    spec:
      containers:
      - name: echo-app
        image: >-
          ba8d9c8fe1374d5bbf5913a537abc1b8.azurecr.io/echoapp:206b9bfc5e14a88925326537d82e998708c1a083
      imagePullSecrets:
        - name: acr-secret-ba8d9c8fe-development
---
kind: Service
apiVersion: v1
metadata:
  name: echo-app-internal
  namespace: development
  labels:
    k8s-app: echo-app
  annotations:
    description: EchoApp
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    k8s-app: echo-app

