apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
  namespace: development
  labels:
    k8s-app: echo-app
  annotations:
    fluxcd.io/automated: "true"
    description: EchoApp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: echo-app
  template:
    metadata:
      name: echo-app
      labels:
        k8s-app: echo-app
      annotations:
        description: EchoApp
    spec:
      containers:
      - name: echo-app
        image: >-
          ba8d9c8fe1374d5bbf5913a537abc1b8.azurecr.io/echoapp:2bda4b5bf8c0aa0a4890ee396347d2c8e57ea169
        env:
        - name: AzureAD__ClientId
          valueFrom:
            secretKeyRef:
              name: echoad-credentials
              key: AzureAD__ClientId
        - name: AzureAD__TenantId
          valueFrom:
            secretKeyRef:
              name: echoad-credentials
              key: AzureAD__TenantId
      imagePullSecrets:
        - name: acr-secret-ba8d9c8fe-development
---
kind: Service
apiVersion: v1
metadata:
  name: echo-app-internal
  namespace: development
  labels:
    k8s-app: echo-app
  annotations:
    description: EchoApp
spec:
  ports:
    - port: 5001
      targetPort: 5001
      name: map-5001-5001
    - port: 443
      targetPort: 5001
      name: map-443-5001
    - port: 80
      targetPort: 5000
      name: map-80-5000
  selector:
    k8s-app: echo-app
---
kind: Service
apiVersion: v1
metadata:
  name: echo-app-external
  namespace: development
  labels:
    k8s-app: echo-app
  annotations:
    description: EchoApp
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      name: map-5001-5001
    - port: 443
      targetPort: 5001
      name: map-443-5001
    - port: 80
      targetPort: 5000
      name: map-80-5000
  selector:
    k8s-app: echo-app

