apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
  namespace: production
  labels:
    k8s-app: echo-app
  annotations:
    fluxcd.io/automated: "true"
    description: EchoApp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: echo-app
  template:
    metadata:
      name: echo-app
      labels:
        k8s-app: echo-app
      annotations:
        description: EchoApp
    spec:
      containers:
      - name: echo-app
        image: >-
          ba8d9c8fe1374d5bbf5913a537abc1b8.azurecr.io/echoapp:af7e449de7250581a596f474a0f5cb8b3fb8c80b
        env:
        - name: AzureAD__ClientId
          valueFrom:
            secretKeyRef:
              name: echoad-credentials
              key: AzureAD__ClientId
        - name: AzureAD__TenantId
          valueFrom:
            secretKeyRef:
              name: echoad-credentials
              key: AzureAD__TenantId
      imagePullSecrets:
        - name: acr-secret-ba8d9c8fe-production
---
kind: Service
apiVersion: v1
metadata:
  name: echo-app-internal
  namespace: production
  labels:
    k8s-app: echo-app
  annotations:
    description: EchoApp
spec:
  ports:
    - port: 5001
      targetPort: 5001
      name: map-5001-5001
    - port: 443
      targetPort: 5001
      name: map-443-5001
    - port: 80
      targetPort: 5000
      name: map-80-5000
  selector:
    k8s-app: echo-app
---
# From https://docs.microsoft.com/en-us/azure/aks/ingress-basic
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-app-ingress-production
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - 20.185.74.145
    secretName: ihfdemo-tls
  rules:
  - https:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: echo-app-internal
            port:
              number: 443
